# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-23 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180910_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='property',
            new_name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
