# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-01 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
