# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-01 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180930_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='subsubcategory',
            name='descriptions',
        ),
    ]
