# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Women Fashion', 'Women Fashion'), ('Men Fashion', 'Men Fashion'), ('Computer and Accessories', 'Computer and Accessories'), ('Phones and Tablets', 'Phones and Tablets'), ('Electronics', 'Electronics'), ('Other Category', 'Other Category')], max_length=300, verbose_name='category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
            preserve_default=False,
        ),
    ]
