# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-03 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181001_0512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Image',
        ),
    ]
