# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-03 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181003_0236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='More_Images',
        ),
    ]
